import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{getFirestore,collection,getDocs,addDoc,updateDoc,deleteDoc,doc,query,orderBy}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import{firebaseConfig}from"/firebase-config.js";
import{SITE_CONFIG}from"/site-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=id=>document.getElementById(id);const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function priceHtml(p){const normal=Number(p.price)||0,discount=Number(p.discountPrice)||0;if(discount>0&&normal>0&&discount<normal)return `<span class="price-old">${rupiah(normal)}</span><span class="price-new">${rupiah(discount)}</span>`;return normal?`<span class="price-new">${rupiah(normal)}</span>`:"-";}
function showPopup(title,message,type="info",action=null){$("popupTitle").textContent=title;$("popupMessage").textContent=message;$("popupIcon").textContent=type==="error"?"!":type==="success"?"✓":"i";$("popupEyebrow").textContent=type==="error"?"ERROR":type==="success"?"SUCCESS":"NOTICE";const b=$("popupAction");b.classList.toggle("hidden",!action);if(action){b.textContent=action.text;b.onclick=()=>{hidePopup();action.fn?.();};}$("sitePopup").classList.remove("hidden");}
function hidePopup(){$("sitePopup").classList.add("hidden");}
$("popupClose").onclick=hidePopup;$("sitePopup").addEventListener("click",e=>{if(e.target===$("sitePopup"))hidePopup();});
if(SITE_CONFIG.logoUrl){$("brandLogo").src=SITE_CONFIG.logoUrl;$("brandLogo").classList.remove("hidden");}if(SITE_CONFIG.backgroundUrl){document.documentElement.style.setProperty("--site-bg-image",`url("${SITE_CONFIG.backgroundUrl.replace(/"/g,'\\"')}")`);document.body.classList.add("custom-bg");}
let editingId=null,editingType=null;
function resetCar(){editingId=null;editingType=null;$("carForm").reset();$("carSubmit").textContent="Simpan Mobil";$("carCancelEdit").classList.add("hidden");}
function resetService(){editingId=null;editingType=null;$("serviceForm").reset();$("serviceSubmit").textContent="Simpan Jasa";$("serviceCancelEdit").classList.add("hidden");}
function startEdit(p){editingId=p.id;editingType=p.category==="jasa"?"service":"car";if(editingType==="car"){$("carForm").classList.remove("hidden");$("serviceForm").classList.add("hidden");document.querySelectorAll(".admin-tab").forEach(x=>x.classList.toggle("active",x.dataset.form==="carForm"));$("carName").value=p.name||"";$("carCategory").value=p.category||"cpm1";$("carSpec").value=p.specification||"";$("carPrice").value=p.price??"";$("carDiscountPrice").value=p.discountPrice??"";$("carStock").value=p.stock??0;$("carImage").value=p.image||"";$("carActive").value=String(!!p.active);$("carSubmit").textContent="Update Mobil";$("carCancelEdit").classList.remove("hidden");}else{$("serviceForm").classList.remove("hidden");$("carForm").classList.add("hidden");document.querySelectorAll(".admin-tab").forEach(x=>x.classList.toggle("active",x.dataset.form==="serviceForm"));$("serviceName").value=p.name||"";$("serviceImage").value=p.image||"";$("serviceDescription").value=p.description||"";$("servicePrice").value=p.price??"";$("serviceDiscountPrice").value=p.discountPrice??"";$("serviceActive").value=String(!!p.active);$("serviceSubmit").textContent="Update Jasa";$("serviceCancelEdit").classList.remove("hidden");}window.scrollTo({top:0,behavior:"smooth"});}
$("loginForm").onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$("email").value,$("password").value);}catch(err){console.error(err);showPopup("Login gagal","Email atau password admin salah, atau Firebase Authentication belum dikonfigurasi.","error");}};
$("logout").onclick=()=>signOut(auth);
document.querySelectorAll(".admin-tab").forEach(tab=>tab.onclick=()=>{if(tab.dataset.form){document.querySelectorAll(".admin-tab").forEach(x=>x.classList.toggle("active",x===tab));$("carForm").classList.toggle("hidden",tab.dataset.form!=="carForm");$("serviceForm").classList.toggle("hidden",tab.dataset.form!=="serviceForm");}});
async function loadAdmin(){try{const snap=await getDocs(collection(db,"products"));const cars=[],services=[];snap.docs.forEach(d=>{const p={id:d.id,...d.data()};if(p.category==="jasa")services.push(p);else cars.push(p);});$("cars").innerHTML=cars.map(p=>`<tr><td>${escapeHtml(p.name)}</td><td>${p.category==="cpm1"?"CPM 1":"CPM 2"}</td><td>${escapeHtml(p.specification||"-")}</td><td>${priceHtml(p)}</td><td>${p.stock??0}</td><td>${p.active?"Aktif":"Nonaktif"}</td><td class="admin-actions"><button class="admin-edit" data-edit="${escapeHtml(p.id)}">Edit</button><button class="danger" data-delete="${escapeHtml(p.id)}">Hapus</button></td></tr>`).join("")||"<tr><td colspan='7'>Belum ada mobil.</td></tr>";$("services").innerHTML=services.map(p=>`<tr><td>${escapeHtml(p.name)}</td><td>${escapeHtml(p.description||"-")}</td><td>${priceHtml(p)}</td><td>${p.active?"Aktif":"Nonaktif"}</td><td class="admin-actions"><button class="admin-edit" data-edit="${escapeHtml(p.id)}">Edit</button><button class="danger" data-delete="${escapeHtml(p.id)}">Hapus</button></td></tr>`).join("")||"<tr><td colspan='5'>Belum ada jasa.</td></tr>";document.querySelectorAll("[data-edit]").forEach(btn=>btn.onclick=async()=>{const d=await getDocs(collection(db,"products"));const found=d.docs.find(x=>x.id===btn.dataset.edit);if(found)startEdit({id:found.id,...found.data()});});document.querySelectorAll("[data-delete]").forEach(btn=>btn.onclick=()=>showPopup("Hapus produk?","Produk ini akan dihapus dari katalog.","error",{text:"Hapus",fn:async()=>{try{await deleteDoc(doc(db,"products",btn.dataset.delete));showPopup("Berhasil","Produk telah dihapus.","success");loadAdmin();}catch(err){console.error(err);showPopup("Gagal menghapus","Periksa Firestore Rules lalu coba lagi.","error");}}}));const orderSnap=await getDocs(query(collection(db,"orders"),orderBy("createdAt","desc")));$("orders").innerHTML=orderSnap.docs.map(d=>{const o=d.data(),item=o.items?.[0];return `<tr><td>${escapeHtml(o.customerName)}</td><td>${escapeHtml(o.phone)}</td><td>${escapeHtml(item?.name||"-")}</td><td>${escapeHtml(o.status||"Baru")}</td></tr>`}).join("")||"<tr><td colspan='4'>Belum ada pesanan.</td></tr>";}catch(err){console.error(err);showPopup("Gagal memuat data","Periksa Firestore Rules dan konfigurasi Firebase.","error");}}
async function saveProduct(form,type){const isCar=type==="car";const data=isCar?{name:$("carName").value,category:$("carCategory").value,specification:$("carSpec").value,price:Number($("carPrice").value),discountPrice:$("carDiscountPrice").value?Number($("carDiscountPrice").value):0,stock:Number($("carStock").value),image:$("carImage").value.trim(),active:$("carActive").value==="true",type:"car"}:{name:$("serviceName").value,category:"jasa",description:$("serviceDescription").value,price:$("servicePrice").value?Number($("servicePrice").value):0,discountPrice:$("serviceDiscountPrice").value?Number($("serviceDiscountPrice").value):0,image:$("serviceImage").value.trim(),active:$("serviceActive").value==="true",type:"service"};if(data.discountPrice&&data.price&&data.discountPrice>=data.price){showPopup("Harga diskon tidak valid","Harga setelah diskon harus lebih kecil dari harga normal.","error");return;}try{if(editingId){await updateDoc(doc(db,"products",editingId),data);if(isCar)resetCar();else resetService();await loadAdmin();showPopup(isCar?"Mobil berhasil diupdate":"Jasa berhasil diupdate","Perubahan sudah disimpan.","success");}else{await addDoc(collection(db,"products"),{...data,createdAt:new Date().toISOString()});form.reset();await loadAdmin();showPopup(isCar?"Mobil berhasil ditambahkan":"Jasa berhasil ditambahkan","Produk sudah masuk ke katalog.","success");}}catch(err){console.error(err);showPopup(editingId?"Gagal mengupdate produk":isCar?"Gagal menambahkan mobil":"Gagal menambahkan jasa","Periksa Firestore Rules.","error");}}
$("carForm").onsubmit=e=>{e.preventDefault();saveProduct(e.target,"car")};$("serviceForm").onsubmit=e=>{e.preventDefault();saveProduct(e.target,"service")};$("carCancelEdit").onclick=resetCar;$("serviceCancelEdit").onclick=resetService;
onAuthStateChanged(auth,user=>{$("login").classList.toggle("hidden",!!user);$("adminPanel").classList.toggle("hidden",!user);$("logout").classList.toggle("hidden",!user);if(user)loadAdmin();});
