import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{getFirestore,collection,getDocs,addDoc,deleteDoc,updateDoc,doc,query,orderBy}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import{firebaseConfig}from"/firebase-config.js";import{SITE_CONFIG}from"/site-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=id=>document.getElementById(id);const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);let editingId=null;
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showPopup(title,message,type="info",action=null){$("popupTitle").textContent=title;$("popupMessage").textContent=message;$("popupIcon").textContent=type==="error"?"!":type==="success"?"✓":"i";$("popupEyebrow").textContent=type==="error"?"ERROR":type==="success"?"SUCCESS":"NOTICE";const b=$("popupAction");b.classList.toggle("hidden",!action);if(action){b.textContent=action.text;b.onclick=()=>{hidePopup();action.fn?.()}}$("sitePopup").classList.remove("hidden")}
function hidePopup(){$("sitePopup").classList.add("hidden")}$('popupClose').onclick=hidePopup;$('sitePopup').addEventListener('click',e=>{if(e.target===$('sitePopup'))hidePopup()});
if(SITE_CONFIG.logoUrl){$("brandLogo").src=SITE_CONFIG.logoUrl}if(SITE_CONFIG.backgroundUrl){document.documentElement.style.setProperty("--site-bg-image",`url("${SITE_CONFIG.backgroundUrl.replace(/"/g,'\\"')}")`);document.body.classList.add("custom-bg")}
function addImageInput(containerId,value=""){const box=$(containerId),row=document.createElement("div");row.className="image-input-row";const input=document.createElement("input");input.type="url";input.placeholder="URL/path gambar dari Imgur";input.value=value;input.autocomplete="off";const remove=document.createElement("button");remove.type="button";remove.className="image-remove-btn";remove.textContent="×";remove.title="Hapus URL";remove.onclick=()=>{row.remove();if(!box.querySelector("input"))addImageInput(containerId)};input.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();addImageInput(containerId);box.lastElementChild.querySelector("input")?.focus()}});row.append(input,remove);box.appendChild(row);return input}
function collectImages(containerId){return[...$(containerId).querySelectorAll("input")].map(i=>i.value.trim()).filter(Boolean)}
function setImages(containerId,images){const box=$(containerId);box.innerHTML="";(images?.length?images:[""]).forEach(x=>addImageInput(containerId,x))}
function resetCar(){editingId=null;$('carForm').reset();setImages('carImages');$('carSubmit').textContent='Simpan Mobil';$('carCancelEdit').classList.add('hidden')}
function resetService(){editingId=null;$('serviceForm').reset();setImages('serviceImages');$('serviceSubmit').textContent='Simpan Jasa';$('serviceCancelEdit').classList.add('hidden')}
function startEdit(p){editingId=p.id;const isCar=p.category!=="jasa";document.querySelectorAll('.admin-tab').forEach(t=>t.classList.toggle('active',t.dataset.form===(isCar?'carForm':'serviceForm')));$('carForm').classList.toggle('hidden',!isCar);$('serviceForm').classList.toggle('hidden',isCar);if(isCar){$('carName').value=p.name||'';$('carCategory').value=p.category||'cpm1';$('carSpec').value=p.specification||'';$('carPrice').value=p.price??'';$('carDiscountPrice').value=p.discountPrice||'';$('carStock').value=p.stock??0;$('carActive').value=String(p.active);setImages('carImages',p.images?.length?p.images:[p.image||'']);$('carSubmit').textContent='Update Mobil';$('carCancelEdit').classList.remove('hidden')}else{$('serviceName').value=p.name||'';$('serviceDescription').value=p.description||'';$('servicePrice').value=p.price??'';$('serviceDiscountPrice').value=p.discountPrice||'';$('serviceActive').value=String(p.active);setImages('serviceImages',p.images?.length?p.images:[p.image||'']);$('serviceSubmit').textContent='Update Jasa';$('serviceCancelEdit').classList.remove('hidden')}window.scrollTo({top:0,behavior:'smooth'})}
async function loadAdmin(){try{const snap=await getDocs(collection(db,"products"));const cars=[],services=[];snap.docs.forEach(d=>{const p={id:d.id,...d.data()};if(p.category==="jasa")services.push(p);else cars.push(p)});$('cars').innerHTML=cars.map(p=>`<tr><td>${escapeHtml(p.name)}</td><td>${p.category==="cpm1"?'CPM 1':'CPM 2'}</td><td>${escapeHtml(p.specification||'-')}</td><td>${p.discountPrice&&p.price?`<span class="price-old">${rupiah(p.price)}</span> ${rupiah(p.discountPrice)}`:rupiah(p.price)}</td><td>${p.stock??0}</td><td>${p.active?'Aktif':'Nonaktif'}</td><td class="table-actions"><button class="admin-edit" data-edit="${escapeHtml(p.id)}">Edit</button><button class="danger" data-delete="${escapeHtml(p.id)}">Hapus</button></td></tr>`).join('')||"<tr><td colspan='7'>Belum ada mobil.</td></tr>`;$('services').innerHTML=services.map(p=>`<tr><td>${escapeHtml(p.name)}</td><td>${escapeHtml(p.description||'-')}</td><td>${p.discountPrice&&p.price?`<span class="price-old">${rupiah(p.price)}</span> ${rupiah(p.discountPrice)}`:p.price?rupiah(p.price):'-'}</td><td>${p.active?'Aktif':'Nonaktif'}</td><td class="table-actions"><button class="admin-edit" data-edit="${escapeHtml(p.id)}">Edit</button><button class="danger" data-delete="${escapeHtml(p.id)}">Hapus</button></td></tr>`).join('')||"<tr><td colspan='5'>Belum ada jasa.</td></tr>`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const p=[...snap.docs].map(d=>({id:d.id,...d.data()})).find(x=>x.id===b.dataset.edit);if(p)startEdit(p)});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>showPopup('Hapus produk?','Produk ini akan dihapus dari katalog.','error',{text:'Hapus',fn:async()=>{try{await deleteDoc(doc(db,'products',b.dataset.delete));await loadAdmin();showPopup('Berhasil','Produk telah dihapus.','success')}catch(err){console.error(err);showPopup('Gagal menghapus','Periksa Firestore Rules lalu coba lagi.','error')}}}));const orderSnap=await getDocs(query(collection(db,'orders'),orderBy('createdAt','desc')));$('orders').innerHTML=orderSnap.docs.map(d=>{const o=d.data(),item=o.items?.[0];return`<tr><td>${escapeHtml(o.customerName)}</td><td>${escapeHtml(o.phone)}</td><td>${escapeHtml(item?.name||'-')}</td><td>${escapeHtml(o.status||'Baru')}</td></tr>`}).join('')||"<tr><td colspan='4'>Belum ada pesanan.</td></tr>"}catch(err){console.error(err);showPopup('Gagal memuat data','Periksa Firestore Rules dan konfigurasi Firebase.','error')}}
function validatePrices(data){return!(data.discountPrice&&data.price&&data.discountPrice>=data.price)}
async function saveProduct(form,type){const isCar=type==='car';const images=collectImages(isCar?'carImages':'serviceImages');const image=images[0]||'';const data=isCar?{name:$('carName').value.trim(),category:$('carCategory').value,specification:$('carSpec').value,price:Number($('carPrice').value),discountPrice:$('carDiscountPrice').value?Number($('carDiscountPrice').value):0,stock:Number($('carStock').value),image,images,active:$('carActive').value==='true',type:'car'}:{name:$('serviceName').value.trim(),category:'jasa',description:$('serviceDescription').value,price:$('servicePrice').value?Number($('servicePrice').value):0,discountPrice:$('serviceDiscountPrice').value?Number($('serviceDiscountPrice').value):0,image,images,active:$('serviceActive').value==='true',type:'service'};if(!validatePrices(data)){showPopup('Harga diskon tidak valid','Harga setelah diskon harus lebih kecil dari harga normal.','error');return}try{if(editingId){await updateDoc(doc(db,'products',editingId),data);if(isCar)resetCar();else resetService();await loadAdmin();showPopup(isCar?'Mobil berhasil diupdate':'Jasa berhasil diupdate','Perubahan sudah disimpan.','success')}else{await addDoc(collection(db,'products'),{...data,createdAt:new Date().toISOString()});if(isCar)resetCar();else resetService();await loadAdmin();showPopup(isCar?'Mobil berhasil ditambahkan':'Jasa berhasil ditambahkan','Produk sudah masuk ke katalog.','success')}}catch(err){console.error(err);showPopup(editingId?'Gagal mengupdate produk':isCar?'Gagal menambahkan mobil':'Gagal menambahkan jasa','Periksa Firestore Rules.','error')}}
$('loginForm').onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('email').value,$('password').value)}catch(err){console.error(err);showPopup('Login gagal','Email atau password admin salah, atau Firebase Authentication belum dikonfigurasi.','error')}};$('logout').onclick=()=>signOut(auth);
document.querySelectorAll('.admin-tab').forEach(tab=>tab.onclick=()=>{if(tab.id==='carCancelEdit'||tab.id==='serviceCancelEdit')return;document.querySelectorAll('.admin-tab').forEach(x=>x.classList.toggle('active',x===tab));$('carForm').classList.toggle('hidden',tab.dataset.form!=='carForm');$('serviceForm').classList.toggle('hidden',tab.dataset.form!=='serviceForm')});document.querySelectorAll('[data-add-images]').forEach(b=>b.onclick=()=>addImageInput(b.dataset.addImages));$('carForm').onsubmit=e=>{e.preventDefault();saveProduct(e.target,'car')};$('serviceForm').onsubmit=e=>{e.preventDefault();saveProduct(e.target,'service')};$('carCancelEdit').onclick=resetCar;$('serviceCancelEdit').onclick=resetService;setImages('carImages');setImages('serviceImages');onAuthStateChanged(auth,user=>{$('login').classList.toggle('hidden',!!user);$('adminPanel').classList.toggle('hidden',!user);$('logout').classList.toggle('hidden',!user);if(user)loadAdmin()});
